/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface_Gráfica;

/**
 *
 * @author 03721174062
 */
public class Acadêmico extends javax.swing.JFrame {

    /**
     * Creates new form Acadêmico
     */
    public Acadêmico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void Exame() {
        LMinExame.setEnabled(true);
        LNotaExame.setEnabled(true);
        ctNotaExame.setEnabled(true);
        LTextoMinExame.setEnabled(true);
        LMédiaFinal.setEnabled(true);
        LTextoMédiaFinal.setEnabled(true); 
        
        

    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LNotas = new javax.swing.JLabel();
        LTextoSomaNotas = new javax.swing.JLabel();
        LTextoMédiaAnual = new javax.swing.JLabel();
        LTextoSituação = new javax.swing.JLabel();
        LTextoMinExame = new javax.swing.JLabel();
        LNotaExame = new javax.swing.JLabel();
        LTextoMédiaFinal = new javax.swing.JLabel();
        ctNota1 = new javax.swing.JTextField();
        ctNota2 = new javax.swing.JTextField();
        ctNota3 = new javax.swing.JTextField();
        LSomaNotas = new javax.swing.JLabel();
        LMédiaAnual = new javax.swing.JLabel();
        LSituação = new javax.swing.JLabel();
        LMinExame = new javax.swing.JLabel();
        LMédiaFinal = new javax.swing.JLabel();
        ctNotaExame = new javax.swing.JTextField();
        botCalcular = new javax.swing.JButton();
        botLimpar = new javax.swing.JButton();
        botSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LNotas.setText("Notas:");

        LTextoSomaNotas.setText("Soma:");

        LTextoMédiaAnual.setText("Média Anual:");

        LTextoSituação.setText("Situação:");

        LTextoMinExame.setText("Mínimo Exame:");
        LTextoMinExame.setEnabled(false);

        LNotaExame.setText("Nota Exame:");
        LNotaExame.setEnabled(false);

        LTextoMédiaFinal.setText("Média Final:");
        LTextoMédiaFinal.setEnabled(false);

        LSomaNotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LMédiaAnual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LSituação.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LMinExame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LMinExame.setEnabled(false);

        LMédiaFinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LMédiaFinal.setEnabled(false);

        ctNotaExame.setEnabled(false);

        botCalcular.setText("Calcular");
        botCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCalcularActionPerformed(evt);
            }
        });

        botLimpar.setText("Limpar");
        botLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimparActionPerformed(evt);
            }
        });

        botSair.setText("Sair");
        botSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LNotaExame)
                                .addGap(18, 18, 18)
                                .addComponent(ctNotaExame, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LTextoSituação)
                                    .addGap(40, 40, 40)
                                    .addComponent(LSituação, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LTextoMinExame)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(LMinExame, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botCalcular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botLimpar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botSair, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LTextoSomaNotas)
                                .addGap(55, 55, 55)
                                .addComponent(LSomaNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LTextoMédiaAnual)
                                .addGap(18, 18, 18)
                                .addComponent(LMédiaAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LTextoMédiaFinal)
                                .addGap(18, 18, 18)
                                .addComponent(LMédiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LNotas)
                                .addGap(18, 18, 18)
                                .addComponent(ctNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ctNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ctNota3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNotas)
                    .addComponent(ctNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LTextoSomaNotas, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(LSomaNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LTextoMédiaAnual)
                    .addComponent(LMédiaAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botLimpar)
                        .addGap(18, 18, 18)
                        .addComponent(botCalcular)
                        .addGap(0, 23, Short.MAX_VALUE)
                        .addComponent(botSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LTextoSituação)
                            .addComponent(LSituação, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LTextoMinExame)
                            .addComponent(LMinExame, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LNotaExame)
                            .addComponent(ctNotaExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LTextoMédiaFinal)
                    .addComponent(LMédiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botSairActionPerformed

    private void botCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCalcularActionPerformed
    boolean Exame = false;
    double N1 = Double.parseDouble(ctNota1.getText());
    double N2 = Double.parseDouble(ctNota2.getText());
    double N3 = Double.parseDouble(ctNota3.getText());  
    
    double Soma = N1 + N2 + N3;
    LSomaNotas.setText(String.format("%.2f", Soma));
    
    double MédiaAnual = Soma / 3;
    LMédiaAnual.setText(String.format("%.2f", MédiaAnual));
    
    if(Soma >= 21.0) {
        LSituação.setText("Aprovado");  
    } else if (MédiaAnual <= 6.9 && MédiaAnual >= 1.7) {
        Exame();
        LSituação.setText("Em Exame");
        double MinExame = (5.0 - (0.6 * MédiaAnual)) / 0.4;
        LMinExame.setText(String.format("%.2f", MinExame));

        
    } else {LSituação.setText("Reprovado");}
    
    if (ctNotaExame.getText() != "") {
        double NotaExame = Double.parseDouble(ctNotaExame.getText());
        
            
    }    
  
    }//GEN-LAST:event_botCalcularActionPerformed
    

    private void botLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimparActionPerformed
        ctNota1.setText(""); ctNota2.setText(""); ctNota3.setText("");
        LSomaNotas.setText(""); LMédiaAnual.setText("");
        LSituação.setText(""); 

    }//GEN-LAST:event_botLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acadêmico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acadêmico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acadêmico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acadêmico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acadêmico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LMinExame;
    private javax.swing.JLabel LMédiaAnual;
    private javax.swing.JLabel LMédiaFinal;
    private javax.swing.JLabel LNotaExame;
    private javax.swing.JLabel LNotas;
    private javax.swing.JLabel LSituação;
    private javax.swing.JLabel LSomaNotas;
    private javax.swing.JLabel LTextoMinExame;
    private javax.swing.JLabel LTextoMédiaAnual;
    private javax.swing.JLabel LTextoMédiaFinal;
    private javax.swing.JLabel LTextoSituação;
    private javax.swing.JLabel LTextoSomaNotas;
    private javax.swing.JButton botCalcular;
    private javax.swing.JButton botLimpar;
    private javax.swing.JButton botSair;
    private javax.swing.JTextField ctNota1;
    private javax.swing.JTextField ctNota2;
    private javax.swing.JTextField ctNota3;
    private javax.swing.JTextField ctNotaExame;
    // End of variables declaration//GEN-END:variables
}
