/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface_Gráfica;

/**
 *
 * @author 03721174062
 */
public class ExerForm extends javax.swing.JFrame {

    /**
     * Creates new form ExerForm
     */
    public ExerForm() {
        initComponents();
    }
    private static boolean botão;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        LProduto = new javax.swing.JLabel();
        LImposto = new javax.swing.JLabel();
        LCotação = new javax.swing.JLabel();
        ctDolar = new javax.swing.JTextField();
        ctValor = new javax.swing.JTextField();
        ctImposto = new javax.swing.JTextField();
        rdTrue = new javax.swing.JRadioButton();
        rdFalse = new javax.swing.JRadioButton();
        LTextoTributação = new javax.swing.JLabel();
        LTextoValorImposto = new javax.swing.JLabel();
        LTextoValorFinal = new javax.swing.JLabel();
        LValorFinal = new javax.swing.JLabel();
        LValorImpostos = new javax.swing.JLabel();
        LTextoPorcenImposto = new javax.swing.JLabel();
        LPorcenImposto = new javax.swing.JLabel();
        botLimpar = new javax.swing.JButton();
        botCalcular = new javax.swing.JButton();
        botSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LProduto.setText("Valor do Produto: ");

        LImposto.setText("Imposto Estadual:");

        LCotação.setText("Cotação do Dólar:");

        rdTrue.setText("Isenta");
        rdTrue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTrueActionPerformed(evt);
            }
        });

        rdFalse.setSelected(true);
        rdFalse.setText("Não Isenta");
        rdFalse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFalseActionPerformed(evt);
            }
        });

        LTextoTributação.setText("Tributação Estadual:");

        LTextoValorImposto.setText("Valor dos Impostos:");

        LTextoValorFinal.setText("Valor Final:");

        LValorFinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LValorImpostos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LTextoPorcenImposto.setText("% de Impostos:");

        LPorcenImposto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botLimpar.setText("Limpar");
        botLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botLimparActionPerformed(evt);
            }
        });

        botCalcular.setText("Calcular");
        botCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botCalcularActionPerformed(evt);
            }
        });

        botSair.setText("Sair");
        botSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LImposto)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ctValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(166, 166, 166))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LCotação)
                            .addComponent(LTextoValorImposto)
                            .addComponent(LTextoValorFinal)
                            .addComponent(LTextoPorcenImposto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LPorcenImposto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ctImposto, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(LValorImpostos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ctDolar))))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdTrue)
                    .addComponent(rdFalse)
                    .addComponent(LTextoTributação, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LTextoTributação)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdTrue)
                        .addGap(1, 1, 1)
                        .addComponent(rdFalse))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LProduto)
                            .addComponent(ctValor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(LImposto))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ctImposto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(LCotação))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ctDolar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LTextoValorImposto)
                            .addComponent(LValorImpostos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LTextoValorFinal)
                            .addComponent(LValorFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LTextoPorcenImposto)
                            .addComponent(LPorcenImposto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(botLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botCalcular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botSair)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdTrueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTrueActionPerformed
        botão = false;
        rdFalse.setSelected(false);

    }//GEN-LAST:event_rdTrueActionPerformed

    private void botSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botSairActionPerformed

    private void botCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botCalcularActionPerformed
        double ValorProduto = Double.parseDouble(ctValor.getText());
        double ImpostoEstadual = Double.parseDouble(ctImposto.getText());
        double cotação = Double.parseDouble(ctDolar.getText());

        double ValorImpostoFederal = ValorProduto * (60.0 / 100.0);
        double ValorImpostoEstadual = 0.0;
        if (!botão) { // Se não é isento
            ValorImpostoEstadual = (ValorProduto + ValorImpostoFederal) * (ImpostoEstadual / 100.0);
        }

        double ValorImpostos = ValorImpostoEstadual + ValorImpostoFederal;
        double ValorImpostosReais = ValorImpostos * cotação;
        LValorImpostos.setText(String.format("%.2f", ValorImpostosReais));

        double ValorFinal = ValorImpostos + ValorProduto;
        double ValorFinalReais = ValorFinal * cotação;
        LValorFinal.setText(String.format("%.2f", ValorFinalReais));

        double PercentualImpostos = (ValorImpostos / ValorFinal) * 100;
        LPorcenImposto.setText(String.format("%.2f", PercentualImpostos) + "%");
    }//GEN-LAST:event_botCalcularActionPerformed

    private void botLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botLimparActionPerformed
        ctValor.setText("");
        ctDolar.setText("");
        ctImposto.setText("");
        LValorImpostos.setText("");
        LValorFinal.setText("");
        LPorcenImposto.setText("");
        
        
        
        
        
    }//GEN-LAST:event_botLimparActionPerformed

    private void rdFalseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFalseActionPerformed
        botão = true;
        rdTrue.setSelected(false);

    }//GEN-LAST:event_rdFalseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LCotação;
    private javax.swing.JLabel LImposto;
    private javax.swing.JLabel LPorcenImposto;
    private javax.swing.JLabel LProduto;
    private javax.swing.JLabel LTextoPorcenImposto;
    private javax.swing.JLabel LTextoTributação;
    private javax.swing.JLabel LTextoValorFinal;
    private javax.swing.JLabel LTextoValorImposto;
    private javax.swing.JLabel LValorFinal;
    private javax.swing.JLabel LValorImpostos;
    private javax.swing.JButton botCalcular;
    private javax.swing.JButton botLimpar;
    private javax.swing.JButton botSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField ctDolar;
    private javax.swing.JTextField ctImposto;
    private javax.swing.JTextField ctValor;
    private javax.swing.JRadioButton rdFalse;
    private javax.swing.JRadioButton rdTrue;
    // End of variables declaration//GEN-END:variables
}
